### ISSUE TITLE
请教下我这边没成功

### ISSUE THREAD

**Issue by sn-625003364** [Coegle/youqian_163_scraper#1]
请求返回{"code":500,"errorMsg":"TOKEN_MISMATCH"}，然后再重新登录，cookie里就没有mail_client_uuid这个字段了
![image](https://user-images.githubusercontent.com/11498057/101981805-6619b600-3caa-11eb-9fb0-b06a7e3ab593.png)

**Comment by Coegle** [comment]
> 请求返回{"code":500,"errorMsg":"TOKEN_MISMATCH"}，然后再重新登录，cookie里就没有mail_client_uuid这个字段了
> ![image](https://user-images.githubusercontent.com/11498057/101981805-6619b600-3caa-11eb-9fb0-b06a7e3ab593.png)

经过测试，mail_client_uuid 字段应该不是必须的字段，可以将其整个删除。
请求返回 500，可能的情况是你没有修改 url 里面的参数，需要和 cookie 里面的 TOKEN 字段相同。
![image](https://user-images.githubusercontent.com/43529970/102006041-b5b6bb00-3d58-11eb-805a-19ba146e9ed3.png)

**Comment by sn-625003364** [comment]
可以了，谢谢，不过我不是token不一致导致的，我用的python2.7版本的，timestamp这个方法没有，我就写死了时间戳上去，时间跨度写的也很大，我现在手动实现了timestamp方法同时把时间跨度缩小，就ok了，没写过python，第一次用感觉真好用，打开了新世界的大门，万分感激

**Comment by Coegle** [comment]
我也是第一次用 Python 写一个完整的小工具，库确实很强大，很高兴能帮到你！
